sonar.projectKey=nmlp
sonar.projectName=NMLP
sonar.projectVersion=1.0.0-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.source=21

sonar.host.url=http://127.0.0.1:9000
sonar.token=sqa_3d34d0cb34a11c9edeb364e106ca1bd02274b23e

sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
